# Generated by Django 3.1.1 on 2020-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flyFrom', models.CharField(max_length=10)),
                ('flyTo', models.CharField(max_length=10)),
                ('id_flight', models.TextField()),
                ('token', models.TextField()),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
